name: Publish on Deno Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build site
        run: deno task build
        env:
          MICROCMS_ENABLE: ${{ vars.MICROCMS_ENABLE }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: blog-elendia-net
          import-map: "./deno.json"
          entrypoint: serve.ts
